#!/bin/zsh

# set clean function
function run_clean() {
    if [ -e "./$1" ]; then
        rm $1
    fi
}

# set failed function
function run_failed() {
    echo -e "\033[41m RUN FAILED \033[0m"
    run_clean $1
    exit 1
}

# check build name
bin_name=$1

# show usage
if [ -z $bin_name ]; then
    echo "Usage: gobr <build name> [sub args]"
    exit 1
fi

# delete first arg
shift

# get sub args
sub_args=$@

# check SIGINT
trap "run_failed $bin_name" INT

# remove old build
run_clean $bin_name

# build file
echo -e "\033[44m START $bin_name \033[0m"
go build "$bin_name.go"

# run file
if [ -e $bin_name ]; then
    chmod +x $bin_name
    eval "./$bin_name $sub_args"
    run_clean $bin_name
    echo -e "\033[42m RUN FINISH \033[0m"
else
    fun_failed $bin_name
fi
